version: '3.8'
services:
  api:
    build: .
    container_name: finanzauto_api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Db_Finanzauto
      DB_USER: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finanzauto_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Db_Finanzauto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
